#!/bin/bash
# ***** script to launch DataExplorer ** 30 Dec 2014 WB *****
#fix Ubuntu Unity problem not displaying sliders set LIBOVERLAY_SCROLLBAR to 0
export LIBOVERLAY_SCROLLBAR=0
#fix GTK3 SWT incompatibility
export SWT_GTK3=0

echo java --add-modules java.xml.bind -D64 -Dfile.encoding=UTF-8 -jar -Xms64m -Xmx3092m ./DataExplorer.jar
echo argument $1
java --add-modules java.xml.bind -D64 -Dfile.encoding=UTF-8 -jar -Xms64m -Xmx3092m ./DataExplorer.jar $1
